name: CTF_Many
main: many1337\CTF\CTF
author: many1337
version: 0.1
api: 
- 1.0.0
- 2.0.0
- 3.0.0
- 4.0.0

commands:
    ctf:
        usage: /ctf <make>
        description: DEB-Command
    ctfstart:
        usage: /ctfstart
        description: DEB-Force-start
        